name: 'which ip （for test only）'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: get ip
        run: |
          curl https://ifconfig.io/ip
          curl https://ifconfig.io/country_code

